- hosts: fridgepi
  vars:
    armversion: 6
    includecamera: true
    loglevel: debug
    timeout_sec: 21600
    adapter_name: # leave blank
    fridge_addr: # leave blank
    pollrate_sec: 2
    servicename: alpicoold
    storagepath: /var/local/homekitdb
    user: pi
  roles:
  - alpicoold
