- hosts: campi
  vars:
    user: pi
    servicename: alpicoold
    loglevel: trace
    pollrate_sec: 2
    timeout_sec: 1800
    storagepath: /var/local/homekitdb
    fridge_addr: # leave blank
    adapter_name: # leave blank
  roles:
  - alpicoold
