# From: https://github.com/brutella/hkcam/blob/master/ansible/roles/hkcam/tasks/configure.yml
---
- name: Update camera config
  become: yes
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^start_x=', line: 'start_x=1' }
    - { regexp: '^gpu_mem=', line: 'gpu_mem=128' }

- name: Disable camera led
  become: yes
  lineinfile:
    dest: /boot/config.txt
    regexp: "^disable_camera_led="
    line: "disable_camera_led=1"
  when: disable_camera_led

- name: Enable camera led
  become: yes
  lineinfile:
    dest: /boot/config.txt
    regexp: "^disable_camera_led="
    line: "disable_camera_led=0"
  when: disable_camera_led == false

- name: Add bcm2835 module
  become: yes
  lineinfile:
    dest: /etc/modules
    regexp: "^bcm2835-v4l2"
    line: "bcm2835-v4l2"
  notify: Reboot pi

- name: Update packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: Reboot
  become: yes
  changed_when: false
  reboot:
    reboot_timeout: 200

- name: Install packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - bc
    - libncurses5-dev
    - ffmpeg
    - raspberrypi-kernel-headers

# Old way of installing v4l2loopback
# - name: Install rpi-source
#   changed_when: false
#   shell: sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update
#
# - name: Install kernel source
#   changed_when: false
#   shell: rpi-source
#
# - name: Install v4l2loopback
#   apt:
#     name: "{{ packages }}"
#     state: present
#   vars:
#     packages:
#     - v4l2loopback-dkms

- name: Download v4l2loopback
  get_url:
     url: https://github.com/umlaeute/v4l2loopback/archive/v0.12.5.tar.gz
     dest: /tmp
  register: v4l2_pkg_download

- name: Extract {{ v4l2_pkg_download }} to /tmp
  unarchive:
    src: "{{ v4l2_pkg_download.dest }}"
    dest: "/tmp"
    remote_src: true
    list_files: true
  register: v4l2_unarchived

- name: Define extracted folder
  set_fact: v4l2_unarchived_dir="/tmp/{{ v4l2_unarchived.files[0] | dirname }}"

- name: Install v4l2loopback from source
  become: yes
  changed_when: false
  shell: cd {{ v4l2_unarchived_dir }} && make && sudo make install && depmod -a

- name: Add v4l2loopback module
  become: yes
  lineinfile:
    dest: /etc/modules
    regexp: "^v4l2loopback"
    line: "v4l2loopback"
